[profile.default]
src = "./starknet"
out = "out"
libs = ["lib"]
solc = "0.6.12"
remappings = [
  "contracts/starkware/solidity=./solidity",
  "contracts/starkware/starknet=./starknet",
  "contracts/starkware/cairo=./cairo",
]
