[profile.default]
src = "src/starkware/starknet/solidity"
out = "out"
libs = ["lib"]
solc = "0.8.27"
evm_version = "cancun"
remappings = ["starkware=src/starkware"]
optimizer = true
optimizer_runs = 200
